# Generated by Django 3.2 on 2021-04-28 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField(max_length=200)),
                ('profession', models.CharField(max_length=122)),
                ('date', models.DateField()),
            ],
        ),
    ]
